# Generated by Django 2.0.3 on 2019-05-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0003_auto_20190514_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
