# Generated by Django 2.0.3 on 2019-05-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0004_auto_20190519_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
