# Generated by Django 2.0.3 on 2019-03-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190322_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
