# Generated by Django 2.0.3 on 2019-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190322_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
