# Generated by Django 2.0.3 on 2019-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190323_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regular_pizza',
            name='topps',
        ),
        migrations.AddField(
            model_name='order',
            name='topps',
            field=models.ManyToManyField(blank=True, related_name='Pizza', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
