# Generated by Django 2.0.3 on 2019-03-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190324_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='top',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
