# Generated by Django 2.0.3 on 2019-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190325_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='top',
        ),
        migrations.AddField(
            model_name='order',
            name='top_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
