# Generated by Django 2.0.3 on 2019-03-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190325_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='top_allowed',
            new_name='topping_allowed',
        ),
        migrations.AddField(
            model_name='order',
            name='topping_number',
            field=models.IntegerField(default=0),
        ),
    ]
