# Generated by Django 2.0.3 on 2019-03-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190325_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='topping_number',
            field=models.IntegerField(default=0),
        ),
    ]
