# Generated by Django 2.0.3 on 2019-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20190326_0614'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='topping_number',
            field=models.BooleanField(default=False),
        ),
    ]
