# Generated by Django 2.0.3 on 2019-03-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190326_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='topping_number_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping_number',
            field=models.IntegerField(default=0),
        ),
    ]
