# Generated by Django 2.0.3 on 2019-03-27 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190327_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
