# Generated by Django 2.0.3 on 2019-03-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regular_pizza',
            old_name='Ptype',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='regular_pizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='regular_pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='large',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='small',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='topps',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
